# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-28 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='storetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(default=b'N/A', max_length=30)),
                ('store_location', models.CharField(default=b'N/A', max_length=50)),
                ('store_owner_name', models.CharField(default=b'N/A', max_length=6)),
            ],
            options={
                'db_table': 'store_table',
            },
        ),
    ]
