# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storetable',
            old_name='store_location',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='storetable',
            old_name='store_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='storetable',
            name='store_owner_name',
        ),
        migrations.AddField(
            model_name='storetable',
            name='password',
            field=models.CharField(default=16, max_length=20),
        ),
    ]
